"""add trainer profile fields

Revision ID: 05fbca528c4c
Revises: b8a69034e0d6
Create Date: 2026-08-25 21:31:51.615101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05fbca528c4c'
down_revision: Union[str, Sequence[str], None] = 'b8a69034e0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainers', sa.Column('location', sa.String(length=500), nullable=True))
    op.add_column('trainers', sa.Column('photo_file_id', sa.VARCHAR(length=255), nullable=True))
    op.add_column('trainers', sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainers', 'social_links')
    op.drop_column('trainers', 'photo_file_id')
    op.drop_column('trainers', 'location')
    # ### end Alembic commands ###
