"""initial schema

Revision ID: 08b8a34ec518
Revises: 
Create Date: 2026-08-19 21:14:19.927340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08b8a34ec518'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('answer', sa.TEXT(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__faq_items'))
    )
    op.create_table('subscription_price_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan', sa.Enum('ONE_MONTH', 'THREE_MONTHS', 'SIX_MONTHS', 'TWELVE_MONTHS', 'INFINITE', name='subscriptionplan'), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__subscription_price_plans')),
    sa.UniqueConstraint('plan', name=op.f('uq__subscription_price_plans__plan'))
    )
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('bio', sa.VARCHAR(length=255), nullable=False),
    sa.Column('notification_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__trainers'))
    )
    op.create_index(op.f('ix__trainers_tg_id'), 'trainers', ['tg_id'], unique=True)
    op.create_table('calendar_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(timezone=True), nullable=False),
    sa.Column('end_time', sa.Time(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('FREE', 'BOOKED', 'BLOCKED', name='slotstatus'), nullable=False),
    sa.Column('source', sa.Enum('TEMPLATE', 'MANUAL', name='slotsource'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('calendar_slots_trainer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__calendar_slots')),
    sa.UniqueConstraint('trainer_id', 'slot_date', 'start_time', name='uq_slot_trainer_date_start')
    )
    op.create_index(op.f('ix__calendar_slots_slot_date'), 'calendar_slots', ['slot_date'], unique=False)
    op.create_index(op.f('ix__calendar_slots_status'), 'calendar_slots', ['status'], unique=False)
    op.create_index(op.f('ix__calendar_slots_trainer_id'), 'calendar_slots', ['trainer_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sport_experience', sa.Enum('NONE', 'UP_TO_3_MONTHS', 'UP_TO_6_MONTHS', 'MORE_THAN_YEAR', name='sport_experience'), nullable=False),
    sa.Column('health_conditions', postgresql.ARRAY(sa.VARCHAR(length=255)), nullable=False),
    sa.Column('health_conditions_other', sa.String(length=1000), nullable=True),
    sa.Column('goals', postgresql.ARRAY(sa.VARCHAR(length=255)), nullable=False),
    sa.Column('health_notes', sa.String(length=1000), nullable=True),
    sa.Column('injuries', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('clients_trainer_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__clients'))
    )
    op.create_index(op.f('ix__clients_tg_id'), 'clients', ['tg_id'], unique=True)
    op.create_index(op.f('ix__clients_trainer_id'), 'clients', ['trainer_id'], unique=False)
    op.create_table('slot_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(timezone=True), nullable=False),
    sa.Column('end_time', sa.Time(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('slot_templates_trainer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__slot_templates'))
    )
    op.create_index(op.f('ix__slot_templates_trainer_id'), 'slot_templates', ['trainer_id'], unique=False)
    op.create_index(op.f('ix__slot_templates_weekday'), 'slot_templates', ['weekday'], unique=False)
    op.create_table('trainer_invite_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('trainer_invite_links_trainer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__trainer_invite_links'))
    )
    op.create_index(op.f('ix__trainer_invite_links_token'), 'trainer_invite_links', ['token'], unique=True)
    op.create_table('trainer_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('ONE_MONTH', 'THREE_MONTHS', 'SIX_MONTHS', 'TWELVE_MONTHS', 'INFINITE', name='subscriptionplan'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', name='subscriptionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('trainer_subscriptions_trainer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__trainer_subscriptions'))
    )
    op.create_index(op.f('ix__trainer_subscriptions_status'), 'trainer_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix__trainer_subscriptions_trainer_id'), 'trainer_subscriptions', ['trainer_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), nullable=False),
    sa.Column('reminder_job_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('bookings_client_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['calendar_slots.id'], name=op.f('bookings_slot_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('bookings_trainer_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__bookings')),
    sa.UniqueConstraint('slot_id', name=op.f('uq__bookings__slot_id'))
    )
    op.create_index(op.f('ix__bookings_client_id'), 'bookings', ['client_id'], unique=False)
    op.create_index(op.f('ix__bookings_trainer_id'), 'bookings', ['trainer_id'], unique=False)
    op.create_table('consultation_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('consultation_type', sa.Enum('FREE', 'PAID', name='consultationtype'), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'DONE', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('consultation_requests_client_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('consultation_requests_trainer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__consultation_requests'))
    )
    op.create_index(op.f('ix__consultation_requests_client_id'), 'consultation_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix__consultation_requests_trainer_id'), 'consultation_requests', ['trainer_id'], unique=False)
    op.create_table('feedback_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=255), nullable=True),
    sa.Column('message', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('feedback_messages_client_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__feedback_messages'))
    )
    op.create_index(op.f('ix__feedback_messages_client_id'), 'feedback_messages', ['client_id'], unique=False)
    op.create_table('program_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('program_type', sa.Enum('SINGLE_SESSION', 'WEEK_3', 'MONTH_2_PER_WEEK', 'MONTH_3_PER_WEEK', name='programtype'), nullable=False),
    sa.Column('direction', sa.Enum('STRENGTH', 'CARDIO', 'ENDURANCE', 'OFP', 'WEIGHT_LOSS', 'CUSTOM_GOAL', name='trainingdirection'), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'DONE', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('program_requests_client_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('program_requests_trainer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__program_requests'))
    )
    op.create_index(op.f('ix__program_requests_client_id'), 'program_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix__program_requests_trainer_id'), 'program_requests', ['trainer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__program_requests_trainer_id'), table_name='program_requests')
    op.drop_index(op.f('ix__program_requests_client_id'), table_name='program_requests')
    op.drop_table('program_requests')
    op.drop_index(op.f('ix__feedback_messages_client_id'), table_name='feedback_messages')
    op.drop_table('feedback_messages')
    op.drop_index(op.f('ix__consultation_requests_trainer_id'), table_name='consultation_requests')
    op.drop_index(op.f('ix__consultation_requests_client_id'), table_name='consultation_requests')
    op.drop_table('consultation_requests')
    op.drop_index(op.f('ix__bookings_trainer_id'), table_name='bookings')
    op.drop_index(op.f('ix__bookings_client_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix__trainer_subscriptions_trainer_id'), table_name='trainer_subscriptions')
    op.drop_index(op.f('ix__trainer_subscriptions_status'), table_name='trainer_subscriptions')
    op.drop_table('trainer_subscriptions')
    op.drop_index(op.f('ix__trainer_invite_links_token'), table_name='trainer_invite_links')
    op.drop_table('trainer_invite_links')
    op.drop_index(op.f('ix__slot_templates_weekday'), table_name='slot_templates')
    op.drop_index(op.f('ix__slot_templates_trainer_id'), table_name='slot_templates')
    op.drop_table('slot_templates')
    op.drop_index(op.f('ix__clients_trainer_id'), table_name='clients')
    op.drop_index(op.f('ix__clients_tg_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix__calendar_slots_trainer_id'), table_name='calendar_slots')
    op.drop_index(op.f('ix__calendar_slots_status'), table_name='calendar_slots')
    op.drop_index(op.f('ix__calendar_slots_slot_date'), table_name='calendar_slots')
    op.drop_table('calendar_slots')
    op.drop_index(op.f('ix__trainers_tg_id'), table_name='trainers')
    op.drop_table('trainers')
    op.drop_table('subscription_price_plans')
    op.drop_table('faq_items')
    # ### end Alembic commands ###
