"""add recurring bookings

Revision ID: 0a65c96fac56
Revises: a9a616fa125d
Create Date: 2026-09-08 19:40:22.531047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a65c96fac56'
down_revision: Union[str, Sequence[str], None] = 'a9a616fa125d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIME(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('recurring_bookings_client_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('recurring_bookings_trainer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__recurring_bookings'))
    )
    op.create_index(op.f('ix__recurring_bookings_client_id'), 'recurring_bookings', ['client_id'], unique=False)
    op.create_index(op.f('ix__recurring_bookings_trainer_id'), 'recurring_bookings', ['trainer_id'], unique=False)
    op.add_column('bookings', sa.Column('recurring_booking_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix__bookings_recurring_booking_id'), 'bookings', ['recurring_booking_id'], unique=False)
    op.create_foreign_key(op.f('bookings_recurring_booking_id_fkey'), 'bookings', 'recurring_bookings', ['recurring_booking_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_recurring_booking_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix__bookings_recurring_booking_id'), table_name='bookings')
    op.drop_column('bookings', 'recurring_booking_id')
    op.drop_index(op.f('ix__recurring_bookings_trainer_id'), table_name='recurring_bookings')
    op.drop_index(op.f('ix__recurring_bookings_client_id'), table_name='recurring_bookings')
    op.drop_table('recurring_bookings')
    # ### end Alembic commands ###
