"""add phone to trainers

Revision ID: 63b98e46fdd5
Revises: a2c31e89f14f
Create Date: 2026-09-06 19:27:21.493042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b98e46fdd5'
down_revision: Union[str, Sequence[str], None] = 'a2c31e89f14f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainers', sa.Column('phone', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainers', 'phone')
    # ### end Alembic commands ###
