"""del health_conditions_other, health_notes, injuries

Revision ID: ae502858869b
Revises: f7a27661375f
Create Date: 2026-08-26 22:57:18.361262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae502858869b'
down_revision: Union[str, Sequence[str], None] = 'f7a27661375f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'health_conditions_other')
    op.drop_column('clients', 'injuries')
    op.drop_column('clients', 'health_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('health_notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('injuries', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('health_conditions_other', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
