"""add trainer_pricing_rule table

Revision ID: b8a69034e0d6
Revises: e9bde64b910b
Create Date: 2026-08-23 20:41:46.439457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a69034e0d6'
down_revision: Union[str, Sequence[str], None] = 'e9bde64b910b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer_pricing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('boundary_time', sa.Time(timezone=True), nullable=False),
    sa.Column('price_before', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('trainer_pricing_rules_trainer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__trainer_pricing_rules'))
    )
    op.create_index(op.f('ix__trainer_pricing_rules_trainer_id'), 'trainer_pricing_rules', ['trainer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__trainer_pricing_rules_trainer_id'), table_name='trainer_pricing_rules')
    op.drop_table('trainer_pricing_rules')
    # ### end Alembic commands ###
