"""add trainer reminder settings

Revision ID: e2dd5c14c0c2
Revises: 0a65c96fac56
Create Date: 2026-09-19 18:26:55.474280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2dd5c14c0c2'
down_revision: Union[str, Sequence[str], None] = '0a65c96fac56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer_reminder_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('hours_before', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('trainer_reminder_settings_trainer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__trainer_reminder_settings'))
    )
    op.create_index(op.f('ix__trainer_reminder_settings_trainer_id'), 'trainer_reminder_settings', ['trainer_id'], unique=True)
    op.add_column('bookings', sa.Column('completion_job_id', sa.VARCHAR(length=255), nullable=True))
    op.add_column('trainer_pricing_rules', sa.Column('trainer_fee', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainer_pricing_rules', 'trainer_fee')
    op.drop_column('bookings', 'completion_job_id')
    op.drop_index(op.f('ix__trainer_reminder_settings_trainer_id'), table_name='trainer_reminder_settings')
    op.drop_table('trainer_reminder_settings')
    # ### end Alembic commands ###
