"""remove trainer location field

Revision ID: f7a27661375f
Revises: 05fbca528c4c
Create Date: 2026-08-25 22:39:43.779234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a27661375f'
down_revision: Union[str, Sequence[str], None] = '05fbca528c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainers', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainers', sa.Column('location', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
