from typing import Protocol

from src.domain.entities.booking import Booking


class BookingRepository(Protocol):
    async def get_all(self) -> list[Booking]: ...
    async def get_by_id(self, booking_id: int) -> Booking | None: ...
    async def get_upcoming_by_client(self, client_id: int) -> list[Booking]: ...
    async def get_upcoming_by_trainer(self, trainer_id: int) -> list[Booking]: ...
    async def count_active_by_slot_id(self, slot_id: int) -> int: ...
    async def count_active_by_slot_ids(self, slot_ids: list[int]) -> dict[int, int]: ...
    async def exists_active_by_client_and_slot(
        self, client_id: int, slot_id: int
    ) -> bool: ...
    async def save(self, booking: Booking) -> Booking: ...
    async def delete(self, booking_id: int) -> None: ...

    async def get_latest_by_recurring_booking_id(
        self, recurring_booking_id: int
    ) -> Booking | None: ...
